name: (development) EKS Karpenter Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "terraform/environments/development/aws/eu-central-1/eks-karpenter/**"
      - "terraform/modules/eks-karpenter/**"

permissions:
  id-token: write
  pull-requests: write
  contents: read
  actions: write

defaults:
  run:
    shell: bash

env:
  terraform-version: 1.10.3
  terraform-directory: "terraform/environments/development/aws"

run-name: ${{ github.workflow }} by @${{ github.actor }} from ${{ github.ref_name }}

jobs:
  terraform_deploy_dev:
    name: Terraform Deploy Development
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform apply
        uses: ./.github/actions/terraform-apply
        with:
          environment: development
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          terraform-directory: "${{ env.terraform-directory }}/${{ secrets.AWS_REGION }}/eks-karpenter"

  retry-on-failure:
    name: Rerun on Fail
    environment: development
    if: failure() && fromJSON(github.run_attempt) < 3
    needs: [terraform_deploy_dev]
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run retry.yml -F run_id=${{ github.run_id }}
